
version: "3.9"

services:
  mongo-express:
    image: mongo-express
    # restart: always
    ports:
      - 8081:${MONGO_EXPRESS_PORT}
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: ${DB_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
    depends_on:
      - db